name: Build and Publish APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: Decode and setup keystore
      env:
        KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}
      run: |
        echo "${KEYSTORE_BASE64}" | base64 -di > my-release-key.keystore
        echo "Keystore created at $(pwd)/my-release-key.keystore"
        echo "KEYSTORE_PATH=$(pwd)/my-release-key.keystore" >> $GITHUB_ENV

    - name: Build Signed APK
      env:
        KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
        KEYSTORE_PATH: ${{ env.KEYSTORE_PATH }}
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      run: ./gradlew assembleRelease -PkeyStorePath=$KEYSTORE_PATH --info

    - name: List build outputs
      run: ls -R app/build/outputs/

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app-release.apk
        path: app/build/outputs/apk/release/app-release.apk
